---
grails:
    profile: angularjs
    codegen:
        defaultPackage: org.modelcatalogue.core
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: true
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
#            xml:
#              - text/xml
#              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            form: application/x-www-form-urlencoded
            html:
                - text/html
                - application/xhtml+xml
            multipartForm: multipart/form-data
            xsl: text/xsl
            xlsx:
                - application/vnd.ms-excel
                - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    databinding:
        dateFormats:
            - MMddyyyy
            - yyyy-MM-dd HH:mm:ss.S
            - yyyy-MM-dd'T'hh:mm:sss'Z'

---
hibernate:
    format_sql: true
    use_sql_comments: true
    generate_statistics: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: org.modelcatalogue.core.security.User
                authorityJoinClassName: org.modelcatalogue.core.security.UserRole
            authority:
                className: org.modelcatalogue.core.security.Role
            requestMap:
                className: org.modelcatalogue.core.testapp.Requestmap
            securityConfigType: Requestmap
            useBasicAuth: true
            basic:
                realmName: 'Model Catalogue'
            filterChain:
                chainMap:
                    -
                        pattern: /catalogue/upload
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: /catalogue/*/*/export
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: /user/current
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: '/api/modelCatalogue/core/feedback/**'
                        filters: 'JOINED_FILTERS,-exceptionTranslationFilter'
                    -
                        pattern: '/**'
                        filters: 'JOINED_FILTERS,-basicAuthenticationFilter,-basicExceptionTranslationFilter'
            logout:
                handlerNames:
                    - rememberMeServices
                    - securityContextLogoutHandler
                    - modelCatalogueSecurityService # both spring security services implements it
---
javamelody:
    # filter out numbers from URI
    http-transform-pattern: \d+
    displayed-counters: 'http,sql,error,log,spring,jsp'
    url-exclude-pattern: '/assets/.*|.*/download.*|.*/gereportDoc.*|.*/changelogDoc.*'
    disabled: true
environments:
    production:
        javamelody:
            disabled: false
---
environments:
    development:
        mc:
            allow:
                signup: true
            preload:
                -
                    name: 'Java Basic Types'
                    url: https://s3-eu-west-1.amazonaws.com/datamodels.metadata.org.uk/Java.mc.xml
    test:
        mc:
            allow:
                signup: true
    production:
        # you can overrides in your mc-config.groovy
        mc:
            sync:
                relationshipTypes: true
            storage: # configure the default storage
               directory: /tmp/mc/storage
               maxSize: 52428800 # 50 * 1024 * 1024
---
grails:
    plugin:
        springsecurity:
            ui:
                register:
                   defaultRoleNames: [] # no roles
--- # Spring Security Core - Debug Filter
environments:
    development:
        grails:
            logging:
                jul:
                    usebridge: true
    test:
        grails:
            logging:
                jul:
                    usebridge: true
    production:
        grails:
            logging:
                jul:
                    usebridge: false
--- # Grails Console
environments:
    development:
        grails:
            plugin:
                console:
                    enabled: true
    test:
        grails:
            plugin:
                console:
                    enabled: true
    production:
        grails:
            plugin:
                console:
                    enabled: false
---
beans:
    apiLegacyInterceptor:
        order: 50
    apiExpiresInterceptor:
        order: 60
    modelCatalogueIDInterceptor:
        order: 70
    springOAuthAjaxFixInterceptor:
        order: 80
---
environments:
    development:
        grails:
            mail:
                disabled: true
